GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "fly"
}

###

DELETE http://localhost:3001/todo/delete/6433bd2014e3372b6a75371d

###

PUT http://localhost:3001/todo/complete/6432b3828040f439e833283c
